name: walker
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.9.19
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - cloudpickle==3.0.0
      - etils==1.5.2
      - farama-notifications==0.0.4
      - filelock==3.15.4
      - fsspec==2024.6.1
      - glfw==2.7.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - imageio==2.34.2
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - mujoco==2.2.0
      - networkx==3.2.1
      - numpy==2.0.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - pillow==10.4.0
      - pygame==2.6.0
      - pyopengl==3.1.7
      - sympy==1.12.1
      - torch==2.3.1
      - tqdm==4.66.4
      - triton==2.3.1
      - typing-extensions==4.12.2
      - zipp==3.19.2
